version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
          MYSQL_ROOT_PASSWORD: your-root-password
          MYSQL_DATABASE: your-database
          MYSQL_USER: your-username
          MYSQL_PASSWORD: your-password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  tests:
    build: .
    depends_on:
      - mysql
    links:
      - mysql

volumes:
  mysql-data:

