name: Python Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
      #    services:
      # mysql:
      # image: mysql:5.7
      #  ports:
      #   - 3306:3306
      #  env:
      #    MYSQL_ROOT_PASSWORD: alpha123 
      #  options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
    steps:
      - uses: actions/checkout@v3
      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get update && sudo apt-get install libcurl4-openssl-dev libmysqlclient-dev && sudo apt-get install -y  mysql-client 

      - name: Setup mysql-action
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306 # Optional, default value is 3306. The port of host
          container port: 3306 # Optional, default value is 3306. The port of container
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mysql version: '5.7' # Optional, default value is "latest". The version of the MySQL
          mysql database: 'test_db' # Optional, default value is "test". The specified database which will be create
          mysql root password: 'root' # Required if "mysql user" is empty, default is empty. The root superuser password
      - name: show charset
        run: |
          sleep 30
          mysql -h 127.0.0.1 --port 3306 -uroot -proot -e "show variables like 'chara%'"

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.110

      - name: Install Poetry
        run: |
          pip3 install poetry && poetry config virtualenvs.create false && poetry install --no-dev

      - name: Install Dependencies
        run: poetry install

      - name: Run tests
        # These environment variables will take precedence over the ones in the Django settings file
        env:
          # Set the DJANGO_SECRET_KEY in the Github repo settings: Go to Secrets and variables > Actions > New repository secret 
          DATABASE_URL: "mysql://root:root@127.0.0.1:3306/test_db"
        run: cd test && poetry run python -m unittest 

