name: Python Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'test_db' # Optional, default value is "test". The specified database which will be create
          mysql user: 'root' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: 'alpha123' # Required if "mysql user" exists. The password for the "mysql user"

    steps:
      - uses: actions/checkout@v3
      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install libcurl4-openssl-dev libmysqlclient-dev 
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.110

      - name: Install Poetry
        run: |
          pip3 install poetry && poetry config virtualenvs.create false && poetry install --no-dev

      - name: Install Dependencies
        run: poetry install

      - name: Run tests
        # These environment variables will take precedence over the ones in the Django settings file
        env:
          # Set the DJANGO_SECRET_KEY in the Github repo settings: Go to Secrets and variables > Actions > New repository secret 
          DATABASE_URL: "mysql://root:alpha123@localhost:3306/test_db"
        run: cd test && poetry run python -m unittest 
